---
- name: Add hashicorp apt key.
  apt_key:
    url: "{{ __nomad_hashicorp_apt_key }}"
    state: present
    validate_certs: true
  tags:
    - prepare

- name: Add hashicorp repo into sources list
  apt_repository:
    repo: "{{ __nomad_hashicorp_apt_repository }}"
    state: present
  tags:
    - prepare

- name: Download common packages  # noqa: command-instead-of-module
  command: >
    apt-get install -y --download-only {{ packages_list | join(' ') }}
  changed_when: false
  tags:
    - prepare
