---
- name: Pin vault release
  template:
    src: "apt.preferences.j2"
    dest: /etc/apt/preferences.d/vault
    mode: 0644

- name: Install common packages
  apt:
    name: "{{ packages_list }}"
    state: present
