---
- name: Prepare remote host remote
  hosts: "hashistack"
  become: true
  gather_facts: false

  tasks:
    - name: Copy rsync dep
      copy:
        src: /var/cache/apt/archives/rsync_3.2.3-4+deb11u1_amd64.deb
        dest: /var/cache/apt/archives/rsync_3.2.3-4+deb11u1_amd64.deb
    
    - name: Copy apt config
      copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list
        
    - name: Install rsync
      shell: >
        apt install --no-download rsync

    - name: Copy cache folder
      synchronize: 
        src: /var/cache/
        dest: /var/cache
        rsync_opts: '-e "ssh -F {{ hs_workspace_root }}/ssh.cfg"'

    - name: Copy apt cache folder
      synchronize: 
        src: /var/lib/apt/lists/
        dest: /var/lib/apt/lists/
        rsync_opts: '-e "ssh -F {{ hs_workspace_root }}/ssh.cfg"'
