---
name: single node install
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default

    steps:
      - name: "Checkout project"
        uses: "actions/checkout@v3"
        with:
          repository: "${{ github.repository }}"
          path: "./"

      - name: "Install project dependencies"
        run: >-
          make prepare

      - name: "Run molecule"
        run: >-
          molecule test
        env:
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_CONTAINERS_BACKEND: "docker"
          ANSIBLE_ROLES_PATH: "/home/runner/work/hashistack/hashistack/roles"

