on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout project"
        uses: "actions/checkout@v3"
        with:
          repository: "${{ github.repository }}"
          path: "./"

      - name: "Install project dependencies"
        run: >-
          mkdir .direnv &&
          make prepare
        env:
          ANSIBLE_COLLECTIONS_PATH: ".direnv"


      - name: "Lint"
        run: >-
          ansible-lint
        env:
          ANSIBLE_COLLECTIONS_PATH: ".direnv"

