on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default

    steps:
      - name: "Checkout project"
        uses: "actions/checkout@v3"
        with:
          repository: "${{ github.repository }}"
          path: "./"

      - name: "Install project dependencies"
        run: >-
          make prepare

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v6.11.0
        with:
          path: "/home/runner/work/hashistack/hashistack"
        env:
          ANSIBLE_ROLES_PATH: "/home/runner/work/hashistack/hashistack/roles"

