on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default

    steps:
      - name: "Checkout project"
        uses: "actions/checkout@v3"
        with:
          repository: "${{ github.repository }}"
          path: "./"

      - name: "Install project dependencies"
        run: >-
          make prepare

      - name: "Lint"
        run: >-
          ansible-lint

